# Site settings
title: Andreas
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Entry site for my blog/project collection. Site is built
  using Jekyll.
  Layout is very simplistic. Not responsive yet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
disqus_shortname: ah223vp

# Build settings
markdown: kramdown
